### PR TITLE
Return the longitude range to [-180°,180°]

### PR DESCRIPTION
**Pull request by eliascarv**

### CODE REVIEW

**Review by juliohm — APPROVED** [review]

**Comment by juliohm** [comment]
@disberd can you please check if this hotfix fixes https://github.com/JuliaGeometry/Meshes.jl/issues/1027 ?

**Comment by disberd** [comment]
@juliohm yes this seems to fix the main issue (so polyareas going around the longitude singularity are split into two polyareas with added edges with the correct longitude sign).

That being said, I believe it would still be desirable to reintroduce the `islon180` function from before #146 and its use in `==` methods for geodetic coordinates as I believe for any purpose you'd want to have `LatLon(x, -180) == LatLon(x, 180)`.

I checked internally that adding this back does not impact the fact that https://github.com/JuliaGeometry/Meshes.jl/issues/1027 is fixed by allowing `lon=-180`

**Comment by juliohm** [comment]
@disberd I think the abstraction we need is the following regarding `==`:

```julia
Point(LatLon(0, -180)) == Point(LatLon(0, 180))
LatLon(0, -180) != LatLon(0, 180)
```

In words: the same point can be represented with different coordinates. The coordinates themselves as lists of numbers are not the same, but the point (which is the physical object in space) is the same. What do you think?

The plan is to merge this PR, release a patch, and then add a special method for `==` of `Point` with `LatLon` in Meshes.jl.

**Comment by disberd** [comment]
@juliohm I see, that indeed makes more sense!

**Comment by juliohm** [comment]
Patch released: https://github.com/JuliaRegistries/General/pull/114086

**Pull request merged**
