### PR TITLE
Adding Irish Transverse Mercator (EPSG:2157)

### PR DESCRIPTION
**Pull request by TimG1964**

### CODE REVIEW

**Comment by TimG1964** [comment]
Tests failed because IRENET95 not defined. This is the datum given on EPSG.io. I don't know how to find the actual one CoordRefSystems needs...
Sorry!

**Comment by juliohm** [comment]
Thank you @TimG1964 ! This datum is not implemented, but is easy to add.

Here is a definition that you can add to the datums.jl file:

```julia
"""
    IRENET95

Ireland 1995 datum.
"""
abstract type IRENET95 <: Datum end

ellipsoid(::Type{IRENET95}) = GRS80🌎
```

I used the information in the same webpage that you used to find the parameters of the CRS.

Can you please add this definition after the `Ire65` datum, and a corresponding test in the `test/datums.jl`? The tests should pass after that.

Please let us know if you have questions.

**Review by juliohm — APPROVED** [review]
Really nice. Thanks for incorporating the suggestions.

**Comment by juliohm** [comment]
Released a patch: https://github.com/JuliaRegistries/General/pull/112365

**Pull request merged**
